# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title Generate Homogeneous Poisson Process
#'
#'@param lambda Numeric value, the intensity.
#'@param T_0 Positive numeric value, the upper bound.
#'
#'@description Generate a homogeneous poisson process with constant intensity \code{lambda} 
#'in time interval \code{[0,T_0]}.
#'
#'@export
gen_homo_poisson <- function(lambda, T_0) {
    .Call('RPPGen_gen_homo_poisson', PACKAGE = 'RPPGen', lambda, T_0)
}

